[project]
name = "double-quant"
version = "0.1.0"
description = "Quantum quantitive finance"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "qiskit>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
